spring.application.name=main-service
app.bootstrap-admin.email=${BOOTSTRAP_ADMIN_EMAIL}
app.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD}

app.bootstrap-admin.first-name=${BOOTSTRAP_ADMIN_FIRST_NAME:Administrador}
app.bootstrap-admin.last-name=${BOOTSTRAP_ADMIN_LAST_NAME:Plataforma do SIG}